[tool.pylint]
"messages control".enable = [
    # "useless-suppression",
    "all",
]
"messages control".disable = [
    # defer to ruff
    "line-too-long",
    "missing-module-docstring",
    "missing-function-docstring",
    "redefined-outer-name",
    "unused-argument",
    "too-complex",
    "missing-param-doc",
    # Silly
    "docstring-first-line-empty",
    "magic-value-comparison",
    # Can be useful to see what is ignored
    "locally-disabled",
    "suppressed-message",
    # Questionable things, but it's ok, I don't need to be told:
    "import-outside-toplevel",
    "superfluous-parens",
    "too-many-lines",
    # Messages that are noisy for now, eventually maybe we'll turn them on:
    "invalid-name",
    # "protected-access",
    "unspecified-encoding",
    "consider-using-f-string",
    "duplicate-code",
    # "cyclic-import",
    # project specific
    "consider-using-enumerate",
    "consider-using-assignment-expr",
    "use-implicit-booleaness-not-comparison-to-zero",
    "protected-access",
    "no-name-in-module",
    "unused-import",
]
basic.no-docstring-rgx = "__.*__|test[A-Z_].*|_decorator|_wrapper|_.*__.*"
classes.defining-attr-methods = [
    "__init__",
    "__new__",
    "__post_init__",
    "setUp",
    "reset",
    "_reset",
]
design.max-args = 35
design.max-attributes = 40
design.max-bool-expr = 5
design.max-branches = 50
design.max-locals = 50
design.max-parents = 12
design.max-positional-arguments = 35
design.max-public-methods = 500
design.max-returns = 20
design.max-statements = 150
design.min-public-methods = 0
design.max-nested-blocks = 7
dunder.good-dunder-names = [ "_repr_html_", "__array__" ]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
